name: check-pdf-manual

# on:
#   workflow_call:
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  check-pdf-manual:
    runs-on: windows-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      _R_CHECK_CRAN_INCOMING_: false
      _R_CHECK_FORCE_SUGGESTS_: false
      _R_CHECK_RD_XREFS_: false
      _R_CHECK_PKG_SIZES_: false

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.1"
          use-public-rspm: true

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-tinytex@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          dependencies: '"hard"'
          pak-version: devel
          extra-packages: |
            any::rcmdcheck
            local::.
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-results: true
          error-on: '"warning"'
          args: c("--as-cran")
          build_args: character()
