name: check-manual

# on:
#   workflow_call:
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

# concurrency:
#   group: ${{ github.workflow }}-${{ github.head_ref }}
#   cancel-in-progress: true

jobs:
  check-manual:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: "3.6"
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          dependencies: '"hard"'
          pak-version: devel
          extra-packages: |
            any::devtools
            local::.

      - name: Build manual
        run: |
          devtools::build_manual()
        shell: Rscript {0}
