name: check-manual

# on:
#   workflow_call:
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

# concurrency:
#   group: ${{ github.workflow }}-${{ github.head_ref }}
#   cancel-in-progress: true

jobs:
  check-manual:
    runs-on: windows-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.1"
          use-public-rspm: true

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-tinytex@v2
        env:
          # install full prebuilt version
          TINYTEX_INSTALLER: TinyTeX

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          dependencies: '"hard"'
          pak-version: devel
          extra-packages: |
            any::devtools
            local::.
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-results: true
          error-on: '"warning"'

      - name: Build manual
        run: |
          Sys.setenv("NOT_CRAN" = "false")
          options(crayon.enabled = TRUE, warn = 2L)
          devtools::build_manual()
        shell: Rscript {0}
