# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
name: R-CMD-check-offline

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Trigger once a week at 00:00 on Sunday
    - cron: "0 0 * * SUN"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  R-CMD-check-offline:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: "3.0"

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: "release"
          http-user-agent: "release"
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          pak-version: devel
          needs: check
          extra-packages: |
            any::rcmdcheck

      - name: Block connectivity
        run: |
          sudo iptables -P OUTPUT DROP
          sudo iptables -A OUTPUT -o lo -j ACCEPT

      - name: Check internet
        run: |
          curl::has_internet()
        shell: Rscript {0}

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          upload-results: true
          #error-on: '"note"'

      - name: Restore connectivity
        run: |
          sudo iptables -F
