# Make sure all examples are run successfully, even the ones that are not supposed
# to be run or tested on CRAN machines. The examples with dummy code should be
# wrapped in `if (FALSE) { ... }`, and this workflow helps find all such instances.
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: test-all-examples

jobs:
  test-all-examples:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          pak-version: devel
          extra-packages: |
            any::devtools
            local::.

      - name: Run examples
        run: |
          options(crayon.enabled = TRUE)
          devtools::run_examples(run_dontrun = TRUE, run_donttest = TRUE)
        shell: Rscript {0}
